[project]
name = "engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Aorius", email = "denis89823613731@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
engineering = "engineering:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
